name: Lint

on:
  push:
    branches:
      - "**"
    tags:
      - "v*"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --locked

      - name: Lint with ruff
        run: uv run ruff check

      - name: Type check with pyright
        run: uv run pyright

      - name: Format with ruff
        run: uv run ruff format --check
