name: Publish

on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      # Configure a constant location for the uv cache
      UV_CACHE_DIR: /tmp/.uv-cache
    permissions:
      contents: write  # IMPORTANT: this permission is mandatory for uploading release assets
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Restore uv cache
        uses: actions/cache@v4
        with:
          path: /tmp/.uv-cache
          key: uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}
          restore-keys: |
            uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}
            uv-${{ runner.os }}
      - name: Build distribution
        run: uv build
      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/vscode_offline-*.tar.gz
            dist/vscode_offline-*.whl
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.13.0
