name: Publish

on:
  push:
    branches:
      - "**"
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: write # IMPORTANT: this permission is mandatory for uploading release assets
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing

    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Build distribution
        run: uv build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: |
            dist/vscode_offline-*.tar.gz
            dist/vscode_offline-*.whl

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: |
            dist/vscode_offline-*.tar.gz
            dist/vscode_offline-*.whl

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.13.0
        if: startsWith(github.ref, 'refs/tags/v')
