name: Test

on:
  push:
    branches:
      - "**"
    tags:
      - "v*"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v5
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a proper tag checkout

      - name: Set up uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --locked

      - name: Lint with ruff
        run: uv run ruff check

      - name: Type check with pyright
        run: uv run pyright

      - name: Format with ruff
        run: uv run ruff format --check

      - name: Run tests with pytest
        run: uv run pytest tests
